### ISSUE TITLE
Addon no longer works with homeassistant 0.96

### ISSUE THREAD

**Issue by chiefcomm** [Mmodarre/pyfujitsu_for_homeassistant#11]
As per title the add on no longer works in hassio 0.96.x, it seems the changes to Climate in 0.96 may have broken the integration for pyfujitsu as there are quite a few climate related issues in 0.96  :-(

The error I'm seeing in logs is "Integration fujitsu_general_heatpump not found when trying to verify its climate platform"

Hope there are some suggestions out there, in the mean time I'm rolling back to 0.95.4 which was last know stable for pyfujitsu ....

https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html

**Comment by leonlmf** [comment]
Very annoying with this 0.96 both of my climate Fujitsu and tuya both got problems

**Comment by lyapich** [comment]
ХА изменили компонент Climate кардинально, в нем проблема. Вот, что в описании: 
<img width="743" alt="Климат" src="https://user-images.githubusercontent.com/52929730/61591939-f4345e80-abd4-11e9-88ff-af9384155372.png">

**Comment by chiefcomm** [comment]
@Mmodarre & @brent0np any chance you gents can help?   I've looked at the climate code changes between 0.95.4 & 0.96.x and frankly my skills with python are completely insufficient to tackle this.  Any assistance you could offer here would be greatly appreciated by those of us using Pyfujitsu.

**Comment by Mmodarre** [comment]
Hi All,

Very glad that the component has helped so many people.

I am aware of breaking changes and for that reason refrained from updating
my HA.

Currently travelling for work and will try to retrofit the code ro new
climate platform once I got the chance. If anyone elese also can help out
it would be much appreciate. More than happy to review the code.

**Comment by graperkins** [comment]
Recently upgraded and having the same problem

"Entity not available: climate.fujitsu_heatpump"

Doesn't matter much during the summer months, but in the winter I rely on Home Assistant Automations to lower the heating temperate when nobody is home and save $$$ on heating cost in Canada.

**Comment by meichthys** [comment]
@Mmodarre Has there been any update on this? I'm still seeing the same error wen trying to validate my configuration:

![image](https://user-images.githubusercontent.com/10717998/71602312-cc530a80-2b25-11ea-9b79-22c467a77c20.png)

There appears to be a pull request (#13)  that would fix this although i haven't been able to verify if the pull request fixes the issue.

**Comment by meichthys** [comment]
Some changes need to be made, but it will work using the changes that are discussed in #14

**Comment by meichthys** [comment]
@chiefcomm  Can we close this now? The more recent issue for this is #16

**Comment by chiefcomm** [comment]
> @chiefcomm Can we close this now? The more recent issue for this is #16

@meichthys sure go ahead and close it - not relevant post the changes made to support later versions.
