### ISSUE TITLE
ClimateDevice is deprecated, modify FujitsuClimate to extend ClimateEntity

### ISSUE THREAD

**Issue by vicfalls** [Mmodarre/pyfujitsu_for_homeassistant#16]
since I updated HASS.io to 0.110.x, I get following warning. I've seen it on other repositories and I guess the code needs to be adjusted.

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:547 
Integration: Climate (documentation, issues) 
First occurred: 12:48:39 (1 occurrences) 
Last logged: 12:48:39

Thanks
Vic

**Comment by pilot1981** [comment]
I think @Mmodarre must fix the code, otherwise in the 0.111 release we can't use it...

**Comment by meichthys** [comment]
This project hasn't been updated in over a year, we may need someone to fork it to move it forward. I know @xerxes87 has created patches for this project in the past.
@xerxes87, would you be willing to fork this project so we can at least merge some pull requests and move the project forward - at least until @Mmodarre returns?

**Comment by Mmodarre** [comment]
Sorry guys I have recently become a dad and that changed my availability and spare time left to do cool things. More than happy for others to make changes and merge back.

**Comment by meichthys** [comment]
@Mmodarre Congrats! 
I'd be willing to help out too, but I'll be a dad soon too, so i don't foresee much spare time in my future ;)
@Mmodarre do you think you'll have time to check for pull requests, or should we fork and merge back in at a later point?

**Comment by vicfalls** [comment]
Has someone tested the current version with HASSIO 0.112 already? Thanks for sharing your experience.

**Comment by chiefcomm** [comment]
> Has someone tested the current version with HASSIO 0.112 already? Thanks for sharing your experience.

Yes I've had no issues since moving to 0.112.x or none that I've noticed - A/C is working perfectly.

**Comment by meichthys** [comment]
Looks like v0.113.x may cause issues:
![image](https://user-images.githubusercontent.com/10717998/88225531-a6fc2a00-cc38-11ea-8ce2-9ee1a41fdbdf.png)

**Comment by pilot1981** [comment]
0.113 need to change code from ClimateDevice to ClimateEntity...

**Comment by chiefcomm** [comment]
> 0.113 need to change code from ClimateDevice to ClimateEntity...

@pilot1981 it's not so easy, I have been running a version of code revised by xerxes87 that was changed already to use  ClimateEntity - that was working up until I upgraded to 0.113.0 today I have rolled back to 0.112.4

**Comment by vicfalls** [comment]
for further details take a look at issue #18
