### ISSUE TITLE
Just FYI regarding API and Fujitsu

### ISSUE THREAD

**Issue by chiefcomm** [Mmodarre/pyfujitsu_for_homeassistant#17]
Thought I'd be cheeky and contact Fujitsu and see if they have any plans to open the API up to the public for developers.

This is the response.

=======================================
Hi Simon,

Sorry, there is currently no plan to supply API to this devise

Please see the ticket from Seiji Fukuda

Our ticket number is 672877 

Kind Regards
Tony
Fujitsu Assist Technical Support

**Comment by meichthys** [comment]
It was worth a shot!  Although they probably won't provide an API, @Mmodarre's efforts on [pyfujitsu](https://github.com/Mmodarre/pyfujitsu) give up pretty much all we need as a starting point. We just need someone with some time to add any desired functionality to the api and then add it to the pyfujitsu homeassistant custom integration. 

A resource that may help with making the pyfujitu api more robust:
https://developer.aylanetworks.com/apibrowser/
The Fglair app doesn't use the api linked above exactly but it does seem to follow the pattern of the api in most respects.

**Comment by liudger** [comment]
Hé just a quick check. Do the Fujitsu airco also have a bsb connection on their board?  Otherwise you could use bsblan board.

**Comment by meichthys** [comment]
@liudger i haven’t seen any bsb ports, but I also haven’t looked inside. I’ll take a look.

**Comment by liudger** [comment]
BSB stands for boiler system bus. So probably it’s not there. But it also supports other connections. 

https://1coderookie.github.io/BSB-LPB-LAN_EN/chap03.html#32-detailed-listing-and-description-of-the-supported-controllers

**Comment by meichthys** [comment]
@chiefcomm Can this issue be closed?

**Comment by chiefcomm** [comment]
> @chiefcomm Can this issue be closed?

@meichthys yes sure it was an FYI not an issue :-)
