### ISSUE TITLE
HASSIO 0.114

### ISSUE THREAD

**Issue by pilot1981** [Mmodarre/pyfujitsu_for_homeassistant#19]
Hi,
anyone can confirm this component work fine also with 0.114?

There is an updated version in some other forked repository?

regards

**Comment by meichthys** [comment]
It appears to be broken again in 0.114

**Comment by chiefcomm** [comment]
I confirm that this component works fine in v114 - you must use the version in the forked repository https://github.com/xerxes87/pyfujitsu_for_homeassistant

**Comment by meichthys** [comment]
@chiefcomm , that's the version i use, but it doesn't seem to be working for me on v0.114.4
It also doesn't show any helpful logs in the home assistant log so I may need to dig deeper to see what's going on.

**Comment by pilot1981** [comment]
I can confirm it working fine with 0.114.4

**Comment by meichthys** [comment]
@pilot1981  Did you make any changes to you config since yesterday? I'm thinking i may be missing something, or it could be that when I re-configured my FGLair app it caused a disconnect.

**Comment by pilot1981** [comment]
no, any changes made...you must use the version in the forked repository https://github.com/xerxes87/pyfujitsu_for_homeassistant

**Comment by meichthys** [comment]
Ok, Thanks. I'll reconfigure my integration.

**Comment by meichthys** [comment]
@pilot1981  I think we can close this issue 👍
