### ISSUE TITLE
Addon no longer works with homeassistant 0.89

### ISSUE THREAD

**Issue by brent0np** [Mmodarre/pyfujitsu_for_homeassistant#2]
Hi @Mmodarre, just an FYI this no longer works due to changes in home assistant 0.89.  It would appear some of the problem is [here](https://community.home-assistant.io/t/0-89-breaking-change-prevent-partial-custom-component-overlays/103728/9)

**Comment by Mmodarre** [comment]
Yes! I realized. Thanks for pointing me to the solution. Hopefully I will make the required changes soon and will let you know to update.

**Comment by brent0np** [comment]
I hope that's the issue.  I tried playing with the code however I have no real experience with Python.  Sorry I couldn't be of more help at this stage.
