### ISSUE TITLE
not working with HA 1.0

### ISSUE THREAD

**Issue by pilot1981** [Mmodarre/pyfujitsu_for_homeassistant#20]
Hi,
after updating to HA version 1.0 (2020.12.7) pyfujitsu devices aren't available...anyone fixed it?

**Comment by meichthys** [comment]
Same here. I haven't had a chance to look at it yet.

**Comment by meichthys** [comment]
Update: It appears that after rebooting HA, it is working again.

**Comment by pilot1981** [comment]
I rebooted many times, but items are always unavailable!

@meichthys which version are you using?

**Comment by chiefcomm** [comment]
@pilot1981 I am running latest version 2020.12.1 the pyfujitsu custom component is working perfectly - no issues at all with upgrade to either 2020.12.0 or 2020.12.1.  I upgraded from 0.118.5 to 2020.12.0 - what version did you upgrade from?

**Comment by pilot1981** [comment]
I'm at 2020.12.7, this is vastest stable version for HASSIO, I done all upgrade steps... 0.118.5->2020.12.0->2020.12.1->2020.12.7

You are able to update to 2020.12.7, this update could have breaking changes for this component?!

**Comment by pilot1981** [comment]
I also have problem with HACS...it could be related to this problem?

**Comment by meichthys** [comment]
> 
> 
> I rebooted many times, but items are always unavailable!
> 
> @meichthys which version are you using?

I'm using the latest version:
![image](https://user-images.githubusercontent.com/10717998/102791304-cf698b00-4374-11eb-9645-12666c1b7e63.png)

HACS was also affected for me. Initially the icon was gone from the left hand menu, and after a reboot, all the custom integrations showed up as new. I had to click the three dot menu at the top right and `dismiss all new repositories`.

**Comment by pilot1981** [comment]
so, you suppose could be a problem related to HACS? 

HACS support say me it's a problem related to SSL, HASSIO isn't able to reach GitHub.com...

**Comment by meichthys** [comment]
The Pyfujitseu problem should not related to HACS since it is not installed using HACS.
The HACS issue was just something we both noticed after updating to the latest version of HA.

**Comment by pilot1981** [comment]
I confirm: problem with HACS created a problem also with this module.

problem HACS solved -> now all works fine.

thanks
