### ISSUE TITLE
Sounds like we need to add a version number soon, warning on HA core 2021.3

### ISSUE THREAD

**Issue by Rydcal** [Mmodarre/pyfujitsu_for_homeassistant#22]
From release notes:

Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.

If you are using a legacy custom integration like custom_components/awesome.py this now needs to move to custom_components/awesome/__init__.py so you can add custom_components/awesome/manifest.json to it.

For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest

For now, this will create a warning on startup. But this will eventually be blocked from loading if it’s missing a version in the manifest.

If you see these warnings, please report the issue with the author of that custom integration.

(@ludeeus - #45919)

**Comment by vicfalls** [comment]
Now it doesn't work with HASS core-2021.3.3 anymore

No 'version' key in the manifest file for custom integration 'fujitsu_general_heatpump'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'fujitsu_general_heatpump'

@brent0np, @Mmodarre do you guys have an idea to fix it?

Thanks
Vic

Update after an additional restart:
connection works and control too.

**Comment by Rydcal** [comment]
Vic, 
Phil updated his branch here: 
https://github.com/xerxes87/pyfujitsu_for_homeassistant

**Comment by vicfalls** [comment]
thanks @Rydcal

**Comment by pilot1981** [comment]
@Rydcal you suggest to delete old componenet and install this one? 
https://github.com/xerxes87/pyfujitsu_for_homeassistant

I already have these files:

custom_components/fujitsu_general_heatpump/init.py
custom_components/fujitsu_general_heatpump/manifest.json


this is my manifest.json:

`{
  "domain": "pyfujitseu_for_homeassistant",
  "name": "Fujitsu general heatpump",
  "documentation": "https://github.com/Mmodarre/pyfujitsu_for_homeassistant/blob/master/README.md",
  "issue_tracker": "https://github.com/Mmodarre/pyfujitsu_for_homeassistant/issues",
  "requirements": ["pyfujitseu"],
  "dependencies": [],
  "after_dependencies": [],
  "codeowners": [
      "@Mmodarre",
      "@xerxes87"
  ],
  "quality_scale": "platinum"
}`

**Comment by Rydcal** [comment]
Yep,  this original branch was last updated in 2019.

**Comment by pilot1981** [comment]
why we can't open issue on repository https://github.com/xerxes87/pyfujitsu_for_homeassistant?

**Comment by pilot1981** [comment]
can we add homekit section to manifest.json?

{
  "homekit": {
    "models": [
      "FUJITSU"
    ]
  }
}

https://developers.home-assistant.io/docs/creating_integration_manifest/

**Comment by meichthys** [comment]
> 
> 
> why we can't open issue on repository https://github.com/xerxes87/pyfujitsu_for_homeassistant?

The maintainer of that fork probably hasn't enabled issues in the github settings. This project is in need of a fork that will accept merge requests. I think the maintainer over at https://github.com/xerxes87/pyfujitsu_for_homeassistant will probably accept pull requests if you can get in contact with him (probably the best bet would be the HA Community Forum)
