### ISSUE TITLE
Addon no longer works with homeassistant 0.92

### ISSUE THREAD

**Issue by chiefcomm** [Mmodarre/pyfujitsu_for_homeassistant#5]
Seems related to several other threads regarding "Unable to find services.yaml for the xxxxxxx integration" related to the new architecture in 0.92.  Not knowing much about Python I couldn't make a lot of sense of the issue however there is a fair amount of chatter on this @ https://github.com/home-assistant/home-assistant/issues/23188

**Comment by brent0np** [comment]
I have created a pull request that I believe will fix this.  Can you please test the below before @Mmodarre approves the pull?  Readme should explain what's required to be changed.

https://github.com/brent0np/pyfujitsu_for_homeassistant

**Comment by chiefcomm** [comment]
@brent0np perfect thanks for your efforts its working well thank you :-)

**Comment by brent0np** [comment]
thanks for letting me know
